### ISSUE TITLE
Callback message is being returned as a string instead of a dictionary

### ISSUE THREAD

**Issue by cindoka** [segmentio/analytics-java#214]
After implementing the callback function, we noticed that the callback message is a string instead of a dictionary (see after "segmentMessage"):

`{"_entity_type":"com.fanduel.segmentpublishing.handling.MessageWrapper","segmentMessage":"TrackMessage{type=track, messageId=f6f01e29-9b07-4907-a8a9-a5f566141193, timestamp=Thu Mar 11 02:07:13 GMT-08:00 2021, context=null, anonymousId=null, userId=101, integrations={}, event=User Created, properties={product=dfs, internal_timestamp=2021-03-11T10:07:12.621Z, event_source=backend, status=live}}"}`

After a wee chat with Oliver, it appears that the node library returns the callback as a dictionary, but the java library returns it as a string, so he recommended to raise this issue here.

**Comment by kierad** [comment]
+1 Having the same issue with the latest version.

**Comment by cindoka** [comment]
@pbassut this is the first time using the callback function, so can't say anything about previous versions :)

**Comment by pbassut** [comment]
May I ask how you're setting callbacks?
I can't reproduce it. I get a Message instance on every callback.

**Comment by cindoka** [comment]
@pbassut This is the code implementation: https://docs.google.com/document/d/1rTXM7OQFT1Lim87DgtnFbpOSlJwDJwxt1cLOVOPxs5Y/edit?usp=sharing

**Comment by cindoka** [comment]
Hi @pbassut ! Just to check if you have an update, please? :)

**Comment by pbassut** [comment]
Not yet. We were working on internal tests to keep the lib stable but since this one seems like a simple fix(I'll still investigate), I'll tackle it next. Sorry for the wait. But should be there ASAP now.

**Comment by pbassut** [comment]
@cindoka Oh, the doc you shared is not accessible by me.
Can you post a gist instead? https://gist.github.com

**Comment by cindoka** [comment]
@pbassut here it is! https://gist.github.com/cindoka/e03af98ab4d224b63e444dbbf32d9186
Let me know if you can't see it

**Comment by pbassut** [comment]
Hi! I needed a reproducible example. But let's talk throught that code you posted.
Looks like I can't use the code you provided since it uses internal stuff.

I noticed that at https://gist.github.com/cindoka/e03af98ab4d224b63e444dbbf32d9186#file-gistfile1-txt-L38-L43 the [message](https://gist.github.com/cindoka/e03af98ab4d224b63e444dbbf32d9186#file-gistfile1-txt-L38) argument should come as an object. Doesn't it?

Or maybe you're [passing it directly to MessageWrapper here](https://gist.github.com/cindoka/e03af98ab4d224b63e444dbbf32d9186#file-gistfile1-txt-L40) and that's stringifying it, since it doesn't know how to represent that object as a string. So it's calling `toString()` in it and that results in of the form you provided in the original post.

If you want a json representation of that object you should use GSON for that.

**Comment by pbassut** [comment]
@kierad can you let me know if that's the same issue that you're experiencing?

**Comment by cindoka** [comment]
@pbassut Using Gson solved our problem, thank you so much!

**Comment by nd4p90x** [comment]
@pbassut Thank you! @cindoka @kierad Comment here if you have any other issues related to this.  Thanks to everyone for working this out!
