### ISSUE TITLE
Queue has reached maxSize

### ISSUE THREAD

**Issue by benorama** [segmentio/analytics-java#31]
Since we have upgraded from 0.4.2 to 1.0.0, we regularly get "Queue has reached maxSize, dropping payload.", around 100 to 200 times a day for our production account (for /agorapulse/manager).

Do you think that the default queue size is not enough?
It looks already pretty big by default (10 000 in the docs).

**Comment by f2prateek** [comment]
This will be fixed in v2. In v2, a background thread reads messages off a BlockingQueue. Once it reads `n` messages (currently configurable as `flushSize`), it wraps it into a Runnable that is submitted to a network Executor (again configurable). So you could set your own network executor that simply ignores batches after a certain size.
